version: 2

sources:
  - name: raw_data
    database: finance_db # your snowflake database
    schema: raw # schema where raw data is stored
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: products
